### ISSUE TITLE
add some flags to avoid bot detection

### ISSUE THREAD

**Issue by johsonluo** [sunshineplan/xxqg#10]
Has notice on your work for sometime.Thank for your work.
There are some configuration used by myself to avoid bot detection. Just for reference only.
----------------------------------------------------------------------
		chromedp.Flag("mute-audio", true),
		chromedp.Flag("disable-gpu", true),
		chromedp.Flag("disable-infobars", true),
		chromedp.Flag("disable-extensions", true),
		chromedp.Flag("no-default-browser-check", true),
		//chromedp.Flag("ignore-certificate-errors", true), 

		//avoid bot detection
		chromedp.Flag("useAutomationExtension", false),
		chromedp.Flag("enable-automation", false),
		chromedp.Flag("excludeSwitches", "enable-automation"), // faked webdriver header

**Comment by sunshineplan** [comment]
Unfortunately, this was not useful.
After adding this codes
```go
ctx, cancel := chromedp.NewExecAllocator(
		context.Background(),
		append(
			chromedp.DefaultExecAllocatorOptions[:],
			chromedp.UserAgent(ua),

			chromedp.Flag("mute-audio", true),
			chromedp.Flag("disable-gpu", true),
			chromedp.Flag("disable-infobars", true),
			chromedp.Flag("disable-extensions", true),
			chromedp.Flag("no-default-browser-check", true),

			chromedp.Flag("useAutomationExtension", false),
			chromedp.Flag("enable-automation", false),
			chromedp.Flag("excludeSwitches", "enable-automation"),
		)...,
	)
```
I still got page like that
![5](https://user-images.githubusercontent.com/11171020/168935294-01e0bbeb-78c5-420a-9d62-650af234709d.png)

**Comment by sunshineplan** [comment]
Actually, I've tried this method before and it still failed.
#### **`xxqg_test.go`**
```go
...

func TestXXQG(t *testing.T) {
	ctx, cancel := chromedp.NewExecAllocator(
		context.Background(),
		append(
			chromedp.DefaultExecAllocatorOptions[:],
			chromedp.UserAgent(ua),
		)...,
	)
	defer cancel()

	ctx, cancel = chromedp.NewContext(ctx)
	defer cancel()

	if err := listenFetch(ctx); err != nil {
		t.Fatal(err)
	}

	if err := chromedp.Run(
		ctx,
		chromedp.ActionFunc(func(ctx context.Context) (err error) {
			_, err = page.AddScriptToEvaluateOnNewDocument(script).Do(ctx)
			return
		}),
	); err != nil {
		t.Fatal(err)
	}

	*token = "xxxxxxxxxxxxxxxxx"
	if err := login(ctx); err != nil {
		t.Fatal(err)
	}

	if err := exam(ctx, practiceURL, "", practiceCount, practiceLimit); err != nil {
		t.Fatal(err)
	}
}
```
#### And modify **`exam.go`** to verify that the script works
```go
...

func exam(ctx context.Context, url, class string, n int, d time.Duration) (err error) {
	//ctx, cancel := chromedp.NewContext(ctx)
	//defer cancel()

	ctx, cancel := context.WithTimeout(ctx, d)
	defer cancel()

	//if err = listenFetch(ctx); err != nil {
	//	return
	//}

...

			if len(nodes) != 0 {
				log.Print("答错 ×")
				var buf []byte
				var webdriver, plugins, userAgent any
				if err = chromedp.Run(
					ctx,
					chromedp.Evaluate("navigator.webdriver", &webdriver),
					chromedp.Evaluate("navigator.plugins", &plugins),
					chromedp.Evaluate("navigator.userAgent", &userAgent),
					chromedp.CaptureScreenshot(&buf),
					chromedp.Click("div.action-row>button.next-btn"),
				); err != nil {
					return
				}
				log.Print(webdriver)
				log.Print(plugins)
				log.Print(userAgent)
				os.WriteFile(fmt.Sprintf("%d.png", i), buf, 0644)
			}

...
```

After running `go test`, Question 5 still got wrong.
I think this is the right way to bypass bot detection, but this script maybe still not enough.

**Comment by johsonluo** [comment]
Do you passed the url test?
https://intoli.com/blog/not-possible-to-block-chrome-headless/chrome-headless-test.html

i have passed the verification, and havn't any problems.

**Comment by johsonluo** [comment]
Maybe you can add the code below somewhere to test:
---------------------------------------------------
	var buf []byte
	if err := chromedp.Run(
		ctx,
		chromedp.ActionFunc(func(ctx context.Context) error {
			var err error
			_, err = page.AddScriptToEvaluateOnNewDocument(byPassDetectScript).Do(ctx)
			if err != nil {
				return err
			}
			return nil
		}),
		chromedp.Navigate("https://intoli.com/blog/not-possible-to-block-chrome-headless/chrome-headless-test.html"),
		chromedp.CaptureScreenshot(&buf),
	); err != nil {
		log.Fatal(err)
	}

	if err := os.WriteFile("screenshot.png", buf, 0644); err != nil {
		log.Fatal(err)
	}

**Comment by sunshineplan** [comment]
> Do you passed the url test? https://intoli.com/blog/not-possible-to-block-chrome-headless/chrome-headless-test.html
> 
> i have passed the verification, and havn't any problems.

Passing the test on this website does not mean passing the test on other websites.

**Comment by sunshineplan** [comment]
XXQG is using aliyun nocaptcha service. I think it's very difficult to bypass anti-bot detection. Close issue.
