### ISSUE TITLE
提点少许的建议

### ISSUE THREAD

**Issue by KB64ba** [sunshineplan/xxqg#7]
可在日志页面加个 登录成功后当前的积分情况并判断需要随机执行那部分，在完成每个步骤后也加载下积分情况，

初步使用发现按你顺序执行没判断积分情况，

**Comment by sunshineplan** [comment]
https://github.com/sunshineplan/xxqg/commit/4d4f862210bf8a1ec7e323803ee95ff8ab9ea001
目前就在登录后以及完成学习后加载积分。
另外，每周答题和专项答题的题库是有限的，所以只要获得过分数就认为已经完成了，而不是做新做一套题库。
