### ISSUE TITLE
怎么在服务器上设置无界面启动

### ISSUE THREAD

**Issue by Zhangxh1011** [sunshineplan/xxqg#9]
怎么在服务器上设置无界面启动
我在服务器上打包完成之后提示
root@e3559f882c14:/xxqg/xxqg-1.0# ./xxqg 
2022/05/09 04:34:15 exec: "google-chrome": executable file not found in $PATH
Press enter key to exit . . .

**Comment by sunshineplan** [comment]
本程序是基于浏览器驱动，而且需要扫码登录的，无界面的话完成不了登录，也没法进行后续的学习。如果只是说运行的话，你要先安装chrome或者chromium，程序会自动在常规位置中寻找。

**Comment by Zhangxh1011** [comment]
> 如果说的话只是驱动程序，而且自动登录的，显示的话无法登录，也不需要浏览本程序进行浏览器完成扫描，基于chrome的学习。中寻找。
我们是不是可以通过一些其他渠道 例如企业微信或者钉钉把二维码发送出来 然后后台运行。这样的话可以封装为docker或者其他方式不是会非常方便吗

**Comment by sunshineplan** [comment]
我不是很明白你的前面一句话的意思。理论上的确可以把二维码保存下来，但是如何发到企业微信或者钉钉我并不熟悉，也没这个打算。或许可以通过保存cookie来完成自动登录，但是失效的时候还是需要扫码登录的。

**Comment by Zhangxh1011** [comment]
cookie的话是24个小时 用无界面启动比较清爽  也可以放在服务器上跑 更加舒服一点

**Comment by sunshineplan** [comment]
浏览器内，token的有效期显示有4小时，期间访问过一次，有效期可以重置到4小时。如果按照这个机制，设置cron每1-3小时运行一次，也许可以达到保持登录状态而无需跳出扫码界面。

**Comment by sunshineplan** [comment]
https://github.com/sunshineplan/xxqg/commit/9537f269757c6651b4fc41fa5fed77df00ce8f80
新版本可以配置使用token启动（命令行加-token xxx，或将token=xxx保存在xxqg.token文件内放在执行文件同一个文件夹），有服务器的可以尝试下配置cron每隔一段时间运行，看能不能保持登录。
没有配置token的话仍旧使用二维码登录，登录成功后会自动保存cookie中的token。
Release内有Linux和Windows的可执行文件，可以直接下载使用。

**Comment by sunshineplan** [comment]
headless模式会引起机器人检测，而服务器可能无法使用非headless模式，所以暂时没法解决
